name: Build Schema Engine
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release --bin schema-engine --target x86_64-unknown-linux-gnu
      - run: tar czf archive.tar.gz target/x86_64-unknown-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: archive.tar.gz
          tag_name: latest
