name: Build Schema Engine
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          tags: my-image:latest
          load: true

      - uses: shrink/actions-docker-extract@v3
        id: extract
        with:
          image: my-image:latest
          path: /app/target/x86_64-unknown-linux-gnu/release/schema-engine
          destination: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/schema-engine
          tag_name: latest
