name: Build Schema Engine
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          tags: my-image:latest
          load: true

      - uses: shrink/actions-docker-extract@v3
        id: extract
        with:
          image: my-image:latest
          path: /app/target/x86_64-unknown-linux-gnu/release/schema-engine
          destination: dist

      # - name: Upload Dist
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: dist

      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable

      # - uses: Swatinem/rust-cache@v2

      # - run: cargo build --release --bin schema-engine --target x86_64-unknown-linux-gnu
      # - run: tar czf archive.tar.gz target/x86_64-unknown-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist
          tag_name: latest
